[variables]
    PHP_VERSION = '8.2'
    NPM_CONFIG_PRODUCTION = 'false'

[phases.setup]
    nixPkgs = ['...', 'php82', 'php82Packages.composer', 'nodejs_20']

[phases.build]
    dependsOn = ['setup']
    cmds = [
        'composer install --no-dev --optimize-autoloader',
        'npm install',
        'npm run build',
        'php artisan config:cache',
        'php artisan route:cache',
        'php artisan view:cache'
    ]

[start]
    cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
